# Configuration for the third agent node
host: "127.0.0.1"
grpc_port: 9094
gossip_port: 9095

# Join the first agent
join_peers:
  - "127.0.0.1:9091"

log_level: "info"
wal_path: "./data/agent3/knowledge.log"



gc_enabled: true
gc_interval_seconds: 10      # Run GC every 10 seconds for fast testing
default_ttl_seconds: 30      # Default TTL (0 means never expires)