# Example configuration for a sutra-agent node.
host: "0.0.0.0"
grpc_port: 9090
gossip_port: 9091

# List of one or more existing agent nodes to join the mesh.
# For the first node, this can be empty.
join_peers: []
  # - "10.0.1.1:9091"

log_level: "info"
wal_path: "./data/knowledge.log"

# TTL and Garbage Collection settings
default_ttl_seconds: 0      # Default TTL for k-paks in seconds (0 = never expires)
gc_enabled: true            # Enable automatic garbage collection of expired k-paks
gc_interval_seconds: 300    # Run garbage collection every 5 minutes
